version: "3.8"
services:
  api:
    container_name: go-infra-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - ${API_PORT}
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  nginx:
    build: ./nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - api
