version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    depends_on:
      - postgres

