version: "3.8"
services:
  api:
    container_name: go-infra-api
    build:
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ".:/usr/src/app"
    command: npm run start:dev
    depends_on:
      - postgres
    expose:
      - ${API_PORT}
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api
      - pgadmin
